[package]
name = "animalese"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coqui-stt = "*"
include_dir = "*"
rodio = "*"

[build-dependencies]
reqwest = { version = "*", features = ["blocking"] }
